package juego;

import herramientas.Lienzo;
import utils.Constantes;

public class JuegoZelda {

	public static void main(String[] args) {
		
//IMPORTANTE: 
		// EXPLICAR LAS COORDENDAS X , Y
		// EXPLICAR LAS DIMENSIONES ANCHO Y ALTO DE LA VENTANA SON: WIDTH = 768 y HEIGHT = 421;	
		
/*ENUNCIADO: 
 * PASO : CARGAR EL PROYECTO, CONFIGURAR LA LIBRERIA API1300 EN EL CLASSPATH
 * PASO : CREAR LA CLASE JuegoImagen.java CON EL METODO MAIN 
 * PASO : SE DEBE CREA UN OBJETO [Imagen.java] CON TRES ATRIBUTOS LAS CORDENADAS X, Y, URL [CONSTRUCTORES, SET Y GET]
 * 		IMPORTANTE CREAR EL METODO ACTUALIZAR
 * PASO : SE DEBE CREA UN OBJETO [Bloque.java] CON TRES ATRIBUTOS LAS CORDENADAS X, Y, URL [CONSTRUCTORES, SET Y GET]
 * PASO : CREAR LA CLASE BLOQUE COMPLETA
 * PASO : CREAR EL OBJETO LIENZO E IMPORTAR LA LIBRERIA LIENZO
 * COMPILAR... SE DEBE VER LA VENTANA EN BLANCO

 * PASO : CREAR UNA INSTANCIA DE IMAGEN CON LAS CORDENADAS Y LA URL DE LA IMAGEN QUE GUSTEN
 * PASO : IMPORTAR LA LIBRERIA IMAGEN
 * COMPILAR.... SE DEBE VER LA VENTANA CON UNA IMAGEN
 *  
 * RETO: 1-UTILIZAR EL CONSTRUCTOR SIN PARAMETROS PARA CREAR LA IMAGEN EN EL CENTRO DEL LIENZO
 * 
 * RETO: 2-UTILIZAR EL CONSTRUCTOR CON PARAMETROS PARA QUE LA IMAGEN SIEMPRE SE VA A CREAR EN LUGARES DISTINTOS AL AZAR EN CUALQUIER LUGAR DEL ESCENARIO, 
 * 		se debe imprimir en un system las cordenadas x,y utilizadas 
 * 
 * RETO: 3-CREAR DOS IMAGENES AL MISMO TIEMPO EN EL ESCENARIO * 
 * 
 * RETO: 4-CREAR 100 IMAGENES AL MISMO TIEMPO EN EL ESCENARIO CON COORDENADAS AL AZAR * 
 * 
 * RETO: 5- UTILIZAR EL OBJETO TECLADO PARA MOVER LA IMAGEN EN LAS 4 DIRECCIONES [Teclado.arriba, Teclado.abajo, Teclado.izquierda, Teclado.derecha]
 * 		EJEMPLO: CREAR EL METODO ACTUALIZAR AGREGAR UN IF E IMPRIMIR EL VALOR DE LA TECLA
 * 
 * RETO: 6- CAMBIAR A UNA IMAGEN DIFERENTE DEPENDIENDO DE LA DIRECCION [Teclado.arriba, Teclado.abajo, Teclado.izquierda, Teclado.derecha]
 * 
 * RETO: 7- LIMITAR EL MOVIMIENTO UNICAMENTE ADENTRO DE LA PANTALLA. 
 * 			- SI LA IMAGEN SALE COMPLETAMENTE DEL AREA VISUAL A LA DERECHA DEBE APARECER EN LA IZQUIERDA Y VICEVERSA. 
 * 			- SI LA IMAGEN SALE COMPLETAMENTE DEL AREA VISUAL HACIA ARRIBA DEBE APARECER DEBAJO Y VICEVERSA. 
 * 
 * RETO: 8- IMPEDIR QUE LA IMAGEN SALGA DEL ESCENARIO SE DEBE DETENER EN LOS BORDES
 * 			- SI LA IMAGEN CHOCA CON LOS LIMITES SUPERIOR, INFERIOR, IZQUIERDA, DERECHA LA IMAGEN NO DEBE DESAPERECER NI CONTINUAR 
 * 
 * ********************** MAPEAR *********************************
 * RETO: 9- IMPRIMIR UN CUADRITO (BLOQUE) CON UNA IMAGEN
 * 
 * RETO: 10- IMPRIMIR UNA FILA COMPLETA DE CUADRITOS (BLOQUE) CON UNA IMAGEN
 * 
 * RETO: 11- MAPEAR UN MAPA UTILIZANDO UNA CADENA DE STRING 
 * 
 * RETO: 12- CREAR UN OBJETO MAPA QUE TENGA EL METODO MAPEAR QUE RECIBE COMO PARAMETRO UNA CADENA DE STRING CON EL MAPA QUE TIENE QUE CREAR 
 * * */
		
		//COMPILAR 1
		Imagen img = new Imagen(250,320,"/img/zelda/link_down.png"); 
		Lienzo lienzo = new Lienzo();
		
		lienzo.agregar(img);;
		//C:\Users\tcken\Desktop\UCR\Intro info\Unidad 6\api1300_FINAL\api1300_FINAL\rec\img\zelda
		//COMPILAR 2
		
		//RETO 1
		
		//RETO 2

		//RETO 3

		//RETO 4

		//RETO 5 - EL CAMBIO SE REALIZA EN EL OBJETO IMAGEN - SE AGREGA EL METODO ACTUALIZAR 	

		//RETO 6 - EL CAMBIO SE REALIZA EN EL OBJETO IMAGEN - SE AGREGA EL METODO ACTUALIZAR 	

		//RETO 7 - EL CAMBIO SE REALIZA EN EL OBJETO IMAGEN - SE AGREGA EL METODO LIMITAR LIMITES 	

		//RETO 8 - LIMITAR EL MOVIMIENTO FUERA DE LA PANTALLA.
	
//**************  MAPEAR ***************
//SOLUCION RETO 9: 

//SOLUCION RETO 10: 		

//SOLUCION RETO 11:
		// ? COMO SABER LA CANTIDAD DE CARACTERES (mapa.length())
		// COMO OBTENER UN CARACTER EN UNA POSICION ESPECIFICA?
		
// SOLUCION RETO 12		

	}

}
